---
title: "jun-explore"
format: html
---

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)

library(tidyverse, warn.conflicts = FALSE)
library(readxl)
library(tidygeocoder)
library(ggplot2)
library(ggrepel)
library(sf)
```


```{r}
leases <- read.csv("2025 ASA DataFest-update2-2025-03-19/Leases.csv")
price_avail <- read.csv("2025 ASA DataFest-update2-2025-03-19/Price and Availability Data.csv")
unemployment <- read.csv("2025 ASA DataFest-update2-2025-03-19/Unemployment.csv")
MMO <- read.csv("2025 ASA DataFest-update2-2025-03-19/Major Market Occupancy Data-revised.csv")
```


```{r}
nyIndustry <- leases |>
  drop_na(internal_industry) |>
  filter(market == "Manhattan")
```

```{r}
nyIndustry$FullAddress = paste(nyIndustry$address, ",", nyIndustry$city, ",", nyIndustry$state, ",", nyIndustry$zip)
nyIndustry$FullAddress

nyIndLatLong <- nyIndustry %>%
  geocode(FullAddress, method = 'osm', lat = latitude , long = longitude)
```


```{r}
ggplot(nyIndLatLong, aes(longitude, latitude), color = "grey99") +
     borders("state") + geom_point() +
     ggrepel::geom_label_repel(aes(label = building_name)) +
     theme_void()
```

