---
title: "exploration sarah"
format: html
---

```{r}
library(tidycensus)
library(tidyverse)
library(ggplot2)
```

```{r}
leases <- read.csv("2025 ASA DataFest-update2-2025-03-19/Leases.csv")
price_avail <- read.csv("2025 ASA DataFest-update2-2025-03-19/Price and Availability Data.csv")
unemployment <- read.csv("2025 ASA DataFest-update2-2025-03-19/Unemployment.csv")
MMO <- read.csv("2025 ASA DataFest-update2-2025-03-19/Major Market Occupancy Data-revised.csv")
```


# Manipulating data: 
```{r}
subset_leases <- leases |> 
  filter(market %in% c("Manhattan") &  leasedSF >= 10000 & internal_industry %in% c("Legal Services", "Financial Services and Insurance", "Technology, Advertising, Media, and Information") & !is.na(direct_available_space) & !is.na(direct_availability_proportion) & !is.na(direct_internal_class_rent) &  !is.na(direct_overall_rent) & !is.na(sublet_available_space) & !is.na(sublet_availability_proportion) & !is.na(sublet_internal_class_rent) & !is.na(sublet_overall_rent)) |>  
  mutate(year_quarter = paste(year, quarter, sep = "_"),
         month = case_when(quarter == "Q1" ~ "01-01",
                           quarter == "Q2" ~ "04-01",
                           quarter == "Q3" ~ "07-01",
                           quarter == "Q4" ~ "10-01"),
         quarter_start = paste(year, month, sep = "-"))

subset_leases$year_quarter <- as.factor(subset_leases$year_quarter) 
subset_leases$quarter_start <- as.Date(subset_leases$quarter_start)
```

**Notes:** 
- A is high quality building, O is otherwise 


```{r}

ggplot(data = subset_leases, aes(x = quarter_start, y = availability_proportion)) + 
  geom_line()
```


```{r}
subset_unemployment <- unemployment |> 
  filter(state %in% c("NY"))
```

```{r}
subset_MMO <- MMO |> 
  filter(market %in% c("Manhattan"))
```

# EDA 

```{r}
subset_leases |> 
  ggplot(aes(x = leasedSF)) + 
  geom_histogram()

subset_leases |> 
  ggplot(aes(x = overall_rent)) + 
  geom_histogram()

subset_leases |> 
  ggplot(aes(x = monthsigned)) + 
  geom_histogram()
```

```{r}
subset_leases |> 
  filter(internal_industry == "Financial Services and Insurance" & market == "Manhattan") |> View()

subset_leases |> 
  filter(internal_industry == "Financial Services and Insurance" & market == "Manhattan") |> 
  ggplot()
```



